# Prueba 2 (Budapest): ego + 2 obstáculos dinámicos.
# Los 3 agentes corren el mismo ftg_control; el ego tiene velocidad_max
# mayor para distinguirse como el auto objetivo, los 2 obstáculos van a
# velocidad moderada. El ego debe completar 10 vueltas consecutivas sin
# colisión con ninguno de los dos.
agents:
  - namespace: ego_racecar
    color: "0.3 0.57 1. 1."
    velocidad_max: 17.0
    sx: 0.0
    sy: 0.0
    stheta: -0.70

  - namespace: obstaculo_1
    color: "1. 0.57 0.1 1."
    velocidad_max: 4.0
    sx: 6.88
    sy: -5.80
    stheta: -0.70

  - namespace: obstaculo_2
    color: "1. 0.1 0.1 1."
    velocidad_max: 4.0
    sx: 11.47
    sy: -9.66
    stheta: -0.70
